name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  push:
    paths:
      - "**.md"

jobs:
  gpt-review:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Japanese
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-4
          PROMPT: |
            あなたは技術記事を書くプロのライターです。回答は日本語でお願いします。
            渡された技術情報について、わかりやすく、読みやすい記事になるようレビューしてください。
            特に以下の点に注意してください:
              - 読者が初心者から中級者であることを想定して、専門用語の説明を含めること
              - 技術的なコンセプトやプロセスをステップバイステップで説明すること
              - 実例やコードサンプルを使って具体的に説明すること
              - 視覚的に分かりやすい図やイラストを追加する提案をすること
              - 重要なポイントを強調し、要点をまとめること
              - 個人的な見解や感想は、客観的事実と異なると分かるようにすること

            誰にとっても理解しやすい技術記事になるよう、積極的に工夫してください。
            あなたに渡される情報は一部分であるため、前提知識が必要な場合にはそれを補足する説明を追加してください。
          top_p: 1
          temperature: 1
          max_tokens: 4096
          MAX_PATCH_LENGTH: 4096
